name:                tleft
version:             2.0.0
github:              "fesanmar/tleft"
license:             MIT License
author:              "Felipe Santa-Cruz"
maintainer:          "fesanmar@gmail.com"
copyright:           "2021 Felipe Santa-Cruz"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
synopsis:            Super naive CLI aplication that subtracts timestamps with the format hh:mm.
category:            CLI

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/tleft#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  tleft-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - tleft

tests:
  tleft-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - tleft
    - hspec
